select * from customer limit 20 ;

-- 1) Total revenue generated by male and female
select gender, SUM(purchase_amount) as revenue
from customer 
group by gender  ;
 
 -- Q2. Which customers used a discount but still spent more than the average purchase amount? 
 select customer_id,purchase_amount
 from customer
 where discount_applied = 'Yes' and purchase_amount >= (select AVG (purchase_amount) from customer) ;
 
 -- Q3. Which are the top 5 products with the highest average review rating?
 SELECT item_purchased, 
       ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type ,
ROUND(AVG(purchase_amount), 2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;
 
 -- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend ,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by avg_spend,total_revenue desc ;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased ,
ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
case 
when previous_purchases= 1 THEN 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer)
select customer_segment, count(*) as 'number of customers'
from customer_type 
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
 with item_counts as(
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
 -- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
 select subscription_status,
 count(customer_id) as 'repeat buyers'
 from customer
 where previous_purchases > 5
 group by subscription_status;
 
 -- Q10. What is the revenue contribution of each age group? 
 select age_group,
 SUM(purchase_amount) as 'Revenue_contribution'
 from customer
 group by age_group
 order by Revenue_contribution desc;